scrape_configs:
  - job_name: 'prometheus-monitoring'
    metrics_path: '/watchers/prometheus'
    scrape_interval: 5s
    static_configs:
#      - targets: ['localhost:8080']
      - targets: ['host.docker.internal:8080']