spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 127608057977-dpcooqq2qq8lu49n6nag1fn7nhdteee9.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          kakao:
            client-id: 3153da86ccec7a41a5327b7da2db0e3f
            client-secret: h99tg1Y1bdGJpT25oU6MPdhFzRUJ6BgD
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao

          naver:
            client-id: YUqxr8aMsKr1GRy537mv
            client-secret: pJN0dsuX3t
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id